name:          CSS Code Guide
fork:          forked from @mdo codeguide.co
description:   Standards for developing flexible, durable, and sustainable CSS, SASS and postCSS.

markdown:      rdiscount
permalink:     pretty
highlighter:   rouge
